question_english = [
  "rooms",
  "private bathrooms",
  "people",
  "queen room",
  "bunk room",
  "accept pets",
  "accept children",
  "parking",
  "restaurant",
  "kitchen",
  "fridges",
  "Wi-Fi",
  "air conditioning",
  "check in time",
  "check in early",
  "check out",
  "late checkout",
  "ocean view rooms",
  "closest beach",
  "nearest grocery store",
  "closest ATM",
  "ferries",
  "buy ferry ticket",
  "ferry dock",
  "Bio Bay reservation",
  "car reservation",
  "golf cart reservation",
  "Uber",
  "riptides",
  "beaches",
  "medical attention",
  "car",
  "golf cart",
  "beach glass",
  "leave car locked",
  "get",
  "best coffee",
  "get coffee",
];

answers_english = [
  "Yes, all of our queen bed rooms have private bathrooms, the only rooms with shared bathrooms are the family rooms",
  "Queen rooms sleep a maximum of two people. For larger parties, please check out our family rooms.",
  "Family rooms sleep 3-4 people (2 on each bed).",
  "We only allow service animals with proper paperwork.",
  "Children must always be supervised. Please be advised that we are attached to a busy bar, which may not be suitable for young children.",
  "There is on-street parking near the bar and guesthouse for cars. If you have a golf cart or scooter, you may park in the guesthouse courtyard area",
  "Yes, our Bar & Restaurant “Lazy Jacks” is open for lunch at 11:00am and stays open late night for dinner.",
  "No, we do not have a kitchen for guests.",
  "No, there are no fridges in the rooms. If you need to store medicine such as insulin or other products, please give us a call at 787-741-5555 to arrange storage.",
  "Yes, Wi-Fi is complimentary with your stay and is available throughout the property.",
  "Yes, there is complimentary air conditioning in all of the rooms.",
  "Check in time is 3:00pm. If you arrive at the property earlier, you are more than welcome to store your bags on the porch in the courtyard area until your room is ready.",
  "Early check in is not guaranteed, we need to give our housekeepers time to clean the rooms after the previous check out.",
  "Check out is 11:00am. If you have a later ferry or plane, you are more than welcome to store your bags in the courtyard area until you need to leave.",
  "Unfortunately we can not grant a late checkout because we need to prepare the room for the next guest.",
  "No, we do not have ocean view rooms, but our guesthouse is only steps away from the beach!",
  "The closest beach (Esperanza Beach) is only about a minute walk",
];

question_mandarin = [
  "客房",
  "私人浴室",
  "人数",
  "大床房",
  "双层床房",
  "允许宠物",
  "允许儿童",
  "停车场",
  "餐厅",
  "厨房",
  "冰箱",
  "Wi-Fi",
  "空调",
  "办理入住时间",
  "提前办理入住",
  "退房时间",
  "延迟退房",
  "海景房",
  "最近的海滩",
  "最近的杂货店",
  "最近的自动取款机",
  "渡轮",
  "购买渡轮票",
  "渡轮码头",
  "生物灯笼湾预订",
  "租车",
  "租高尔夫球车",
  "优步",
  "激流",
  "海滩",
  "医疗救护",
  "汽车",
  "高尔夫球车",
  "海滩玻璃",
  "离开时锁好车门",
  "获取",
  "最好的咖啡",
  "喝咖啡",
];

answers_mandarin = [
  "是的，我们所有的大床房都有私人浴室，唯一没有私人浴室的是家庭房。",
  "大床房最多可容纳两个人。对于较大的派对，请查看我们的家庭房。",
  "家庭房可容纳3-4人（每张床上2人）。",
  "我们只允许带有合法文件的服务动物。",
  "孩子必须时刻受到监督。请注意，我们的酒吧很忙，可能不适合年幼的孩子。",
  "酒吧和宾馆附近有路边停车场。如果您有高尔夫球车或摩托车，可以在宾馆庭院区域停放。",
  "是的，我们的酒吧餐厅“Lazy Jacks”中午11:00开门营业，并为晚餐保持营业至深夜。",
  "不，我们没有提供给客人使用的厨房。",
  "不，房间里没有冰箱。如果您需要存放胰岛素或其他药物，请致电787-741-5555安排存储。",
  "是的，Wi-Fi与您的住宿一起免费提供，并可在整个物业范围内使用。",
  "是的，所有的房间都有免费空调。",
  "办理入住时间为下午3:00。如果您早些到达物业，可以将您的行李放在庭院区的门廊上，直到您的房间准备好为止。",
  "无法保证提前入住，我们需要给我们的客房服务人员时间清洁之前的房间。",
  "退房时间为上午11:00。如果您有较晚的渡轮或飞机，可以将您的行李存放在庭院区，直到您需要离开为止。",
  "不幸的是，我们无法延迟退房，因为我们需要为下一个客人准备房间。",
  "不，我们没有海景房，但我们的宾馆距离海滩只有几步之遥！",
  "最近的海滩（Esperanza Beach）只需步行约一分钟即可到达。",
];

question_spanish = [
  "habitaciones",
  "baños privados",
  "personas",
  "habitación con cama queen",
  "habitación con literas",
  "admiten mascotas",
  "admiten niños",
  "estacionamiento",
  "restaurante",
  "cocina",
  "neveras",
  "Wi-Fi",
  "aire acondicionado",
  "hora de entrada",
  "registrarse temprano",
  "hora de salida",
  "salida tardía",
  "habitaciones con vista al mar",
  "playa más cercana",
  "tienda de comestibles más cercana",
  "cajero automático más cercano",
  "transbordadores",
  "comprar boleto de transbordador",
  "muelle de transbordadores",
  "reservación para la Bahía Bioluminiscente",
  "reservación de auto",
  "reservación de carrito de golf",
  "Uber",
  "corrientes peligrosas",
  "playas",
  "atención médica",
  "auto",
  "carrito de golf",
  "vidrio de playa",
  "dejar el auto cerrado con llave",
  "conseguir",
  "el mejor café",
  "conseguir café",
];

answers_spanish = [
  "Sí, todas nuestras habitaciones con cama queen tienen baños privados, las únicas habitaciones con baños compartidos son las habitaciones familiares.",
  "Las habitaciones con cama queen alojan un máximo de dos personas. Para grupos más grandes, por favor revisa nuestras habitaciones familiares.",
  "Las habitaciones familiares alojan de 3 a 4 personas (2 en cada cama).",
  "Solo permitimos animales de servicio con la documentación adecuada.",
  "Los niños siempre deben estar supervisados. Por favor tenga en cuenta que estamos junto a un bar concurrido, lo que puede no ser adecuado para niños pequeños.",
  "Hay estacionamiento en la calle cerca del bar y la posada para autos. Si tienes un carrito de golf o una moto, puedes estacionarlo en el área del patio de la posada.",
  "Sí, nuestro Bar y Restaurante “Lazy Jacks” está abierto para el almuerzo a las 11:00 am y permanece abierto hasta tarde para la cena.",
  "No, no tenemos una cocina para huéspedes.",
  "No, no hay neveras en las habitaciones. Si necesitas almacenar medicamentos como insulina u otros productos, por favor llámanos al 787-741-5555 para hacer arreglos de almacenamiento.",
  "Sí, el Wi-Fi es gratuito durante tu estadía y está disponible en toda la propiedad.",
  "Sí, hay aire acondicionado gratuito en todas las habitaciones.",
  "La hora de registro es a las 3:00 pm. Si llegas antes, eres más que bienvenido a dejar tus maletas en el porche del área del patio hasta que tu habitación esté lista.",
  "El registro temprano no está garantizado, necesitamos darle tiempo a nuestros empleados de limpieza para limpiar las habitaciones después de la salida anterior.",
  "La hora de salida es a las 11:00 am. Si tienes un ferry o avión más tarde, eres más que bienvenido a dejar tus maletas en el área del patio hasta que necesites irte.",
  "Desafortunadamente no podemos conceder una salida tardía porque necesitamos preparar la habitación para el próximo huésped.",
  "No, no tenemos habitaciones con vista al mar, ¡pero nuestra posada está a solo unos pasos de la playa!",
  "La playa más cercana (Playa Esperanza) está a solo aproximadamente un minuto caminando.",
  "La tienda de comestibles más cercana está a solo 5 minutos en coche.",
  "El cajero automático más cercano está a solo 5 minutos en coche.",
  "Los transbordadores salen desde el muelle de Esperanza, a solo 5 minutos en coche de la posada.",
];
